Build:
	gcc src/Bank_structure.h src/Bank_Function.h src/authenticate.c src/Check_Data.c src/Create_Account.c src/Login_Acc.c src/User_Action.c src/action.c src/main.c 
Test:
	gcc test/test.c -Iunity
Windows:
	gcc Main_Bank_Management.c
Run:
	./a.out
