Build:
	gcc src/Bank_structure.h src/Bank_Function.h src/authenticate.c src/Check_Data.c src/Create_Account.c src/Login_Acc.c src/User_Action.c src/action.c src/main.c 
Test:
	gcc test/Bank_Function.h test/test.c Unity/unity.c -Iunity

Run:
	./a.out
